name: swift-format

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  format:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Install swift-format
        run: brew install swift-format
      - name: Run swift-format
        run: swift-format . --in-place --recursive --configuration .swift-format
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: run swift-format
          delete-branch: true
          title: Run swift-format
          reviewers: ski-u
          branch: run-swift-format
